In [2]:
import torch
import numpy as np
import sys
from latent_net import *

In [3]:
from torch.autograd.functional import hessian

In [4]:
def pow_reducer(x):
    return x.pow(3).sum()

In [11]:
inputs = torch.rand(2, 2)
print(inputs)

tensor([[0.2024, 0.8144],
        [0.2066, 0.1278]])


In [12]:
print(pow_reducer(inputs))

tensor(0.5593)


In [13]:
hessian(pow_reducer, inputs)

tensor([[[[1.2145, 0.0000],
          [0.0000, 0.0000]],

         [[0.0000, 4.8861],
          [0.0000, 0.0000]]],


        [[[0.0000, 0.0000],
          [1.2396, 0.0000]],

         [[0.0000, 0.0000],
          [0.0000, 0.7670]]]])

In [9]:
a = np.array([1, 2, 3])
b = np.array([3, 4, 5])

a_n = a / np.linalg.norm(a)
b_n = b / np.linalg.norm(b)

In [11]:
a_n

array([0.26726124, 0.53452248, 0.80178373])

In [12]:
b_n

array([0.42426407, 0.56568542, 0.70710678])

In [10]:
# np.corrcoef(a, b)

print(np.cov(a_n, b_n))

[[0.07142857 0.03779645]
 [0.03779645 0.02      ]]
